apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-replica-cm1
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: mysql-replica
data:
  init.sql: |
    USE app;

    CHANGE REPLICATION SOURCE TO
      SOURCE_HOST='mysql-source',
      SOURCE_USER='slave_user',
      SOURCE_PASSWORD='password',
      SOURCE_AUTO_POSITION=1,
      SOURCE_SSL=1,
      SOURCE_SSL_CA='/etc/mysql/certs/ca-cert.pem',
      SOURCE_SSL_CERT='/etc/mysql/certs/client-cert.pem',
      SOURCE_SSL_KEY='/etc/mysql/certs/client-key.pem';

    START REPLICA;

