apiVersion: v1
data:
  client-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDTjCCAjYCAQIwDQYJKoZIhvcNAQELBQAwazELMAkGA1UEBhMCVVMxDjAMBgNV
    BAgMBVN0YXRlMQ0wCwYDVQQHDARDaXR5MRUwEwYDVQQKDAxPcmdhbml6YXRpb24x
    EzARBgNVBAsMCkRlcGFydG1lbnQxETAPBgNVBAMMCE15U1FMLUNBMB4XDTI0MTEy
    NDExNDI0OFoXDTM0MTEyMjExNDI0OFowbzELMAkGA1UEBhMCVVMxDjAMBgNVBAgM
    BVN0YXRlMQ0wCwYDVQQHDARDaXR5MRUwEwYDVQQKDAxPcmdhbml6YXRpb24xEzAR
    BgNVBAsMCkRlcGFydG1lbnQxFTATBgNVBAMMDG15c3FsLWNsaWVudDCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBAM94MIKtnSgaVRcZ5BoQTDtkhsbUeCMc
    QGRJQQEmpfZRd7gOR/VdK3FGimeOOG/qZleqe0JyReqzKV3z1HmLQTkb9dLncI/+
    cLgcIt8xFkrIay2v+TsAMk7KPnh9mxBbQJ35DHh8kZiTvdWpujxzejnB9FDQ+X+0
    bJqzWKE0XcFJrx3yEirevMBto5pNy1fW8c1IuaxXRVM5sH+J+aIux9sktz4sG4Gq
    I22lhxPGHFY1iB1OUmj0zXby5gnnFt55iTP34vHTfVZXFz5XMO09vVpKxyXWxqSi
    IWexS8Qrzlta7KplisyZ+kUmO75q7ExRikeUFHi2Vh6JbIWAJ3PVsIsCAwEAATAN
    BgkqhkiG9w0BAQsFAAOCAQEAa2ZKP+RMEM8Vf9DXX5N+qWLncj+Cvl3P1agPnEfB
    q1P1ukxdIk5WTlq+pb1QEjRAtIp7GwUOY5AD2eX0mlWDw3wj4xEVfJZUwRDZzRJS
    M2l/QGWaZVFnb04t8+R8GeyVgdwN+dGABV/vOSuMHzeEtll62F0rivOYW8vhwbcE
    NOeWpYOpIIoCVYiO2R4JFNJhaLO1mu/rUHavqrJ3CAj8lt3ysh6UHH7ecPLoVuuc
    jJTKKA/ObaM1qLEm/iFd++VPBSDeYH2AU7IfGj0kiCmZuxLO1F00cOGiN6/W8Srl
    E/hZrv29MTnZEJer2gtaDjBcATgB7TyQYgpshtw5AYi8Nw==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: mysql-replica
  name: mysql-replica-cm3
