apiVersion: v1
data:
  server-key.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCVS+fcjfwMwLGU
    2K8BXw5FW4jjS6Gl6rarqPvU3nSKAt3D5Pxc3mtxhA5jF1FMcqupvdqJ64e1eA/H
    34IYlCPn3v4FjwRQjqqObbbt/L5gBdxB3hlbeZ2Ry/pv5QB67LsrpXmQFanu0jZj
    sljxSLujKCjP8lnM87jvflbxiIdl777fQoybRmxwnUkwrPho9MC4rCvkbINd11BX
    ZNcjvGYotOSgzSwHErMcWEaxgWDneJ2hnlaUiWYfKHcpf2BiRkzjY7hZ8uL5wKmz
    cL4XxyqSNbaCucvcoTs7BfLfwLpQ6PEKwaq9FM3jc2pudYp9LsMnWC+874Go39Az
    wSQVWnyfAgMBAAECggEAKNzNOdssxQrKsAw8nhn3zHj4twmA1WowFDzcrI80g3+0
    VgUrI3oHG1tDGtELgeqS3JMnqP8rtjoFy7V7pKGLUFAC49+YlTnvKauS2YGHU73W
    4rpY42YegAS953lcz8hSlGgmpQ6g48pqc5Ahcuzu2oHH5d6VwJhmojpIrrQpJvd0
    FFKMBYwviEtchySGLguYPdWXwG3ZbXql/cg3wsT4BW9FdqiXXvXLT1C0fly4Yq4g
    qqR1rUEHVTEkKd5vYu/ZnahFplW8wpwJ9Re0oqi2DeUvpZdWEGBWO/3wbfSp63bJ
    /lniuyp3GATO6FQUTVJl9ZQj8ZexiIG2r1G+2sak9QKBgQDG9V6rVOlEowH+hv6d
    rmVZUTILXqSEOgKgPQurZCseQMRTJbj3eQft863eHIc+qIH5yTVfKuL3RO/I44oJ
    21OaXhVDDRwPy0BEtw6Cryh0FW4O9NTMaRCD8wqqWzNcpaJQlls7TP3lxL1Clzyk
    omfnvBYShL0dmqjz9W6VYwYDewKBgQDAGZPWxPy9yRkmXMxbMQw03m1z1XHh/gfq
    t9WbHHWPmgaiR5e7yyFLVy1a1IMRZHSIluwTo6P78nvaWfzFG1Bl38FmEhV4M4Vc
    L3lvSdv+KKTzu6oTGcL1SZAyNJJkLqqAU7DiAszwhOYcHyNPWIltZ8KfwMTGUFif
    5uMvY62gLQKBgCdDIrSC5Cm0VV9qOnLZiIyQtmSB/8tMO1pt0ZC4Cr5En7mc1xyX
    GNZ/YQ9U5+eYj1XAvDSUnQeY5gzpwkLhsmTjLiT2QFRpkrw8t7NYZ45I8FgpPpk8
    HpM7ch5eMwuUcCyhD03riqs+IO80MzZ2CjUz69MpuLxP2gmSpIj8aqJjAoGAEgkU
    uUBLXmIoC1MBGLq1I62SZyKuC4K3KZFS67ozS2UxpEDGfSooGRO5PWLgX1yoGD7b
    MUjW14u/lxOFyNe0p6vnU3b1LxDfP3VxmEI99lHIkt2WrS5pAHCEqkIHUIKVHXE+
    FSogJaDEnfVKcmOkm3H3cto9X0Uh3PlncQaRwY0CgYARDSIlMnHe3GrBneuBvGPy
    7mYysCZHNzttl6Q8DSDVIK39VKkWkyNW8cYbxVU18qtNCS64KosrU4/qdRoDOmZZ
    6zNg7UqhkZ8O5McrdX37GzdzZtn/huVElvj9x3qrmnYXqFsvwGYSTqP+R2IoLItq
    zB7d6IoQFr0Ajq7Z0oCEeg==
    -----END PRIVATE KEY-----
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: mysql-source
  name: mysql-source-cm5
